server:
  port: 8082

dubbo:
  application:
    name: api-gateway-test
    version: 1.0.0
  registry:
#    docker
    address: zookeeper://host.docker.internal:2181
#    local
#    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.melo.rpc